server:
  port: ${PORT:0}
spring:
  application:
    name: members-service
#mongodb
  data:
    mongodb:
      uri: mongodb+srv://weichafe:im28zeta@clusterteamweichafe.jqyo2.mongodb.net/db_team_weichafe?retryWrites=true&w=majority
      database: db_team_weichafe
#swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    tagsSorter: alpha
    display-query-params-without-oauth2: true
    use-root-path: true
  cache:
    disabled: true
#jackson
  jackson:
    time-zone: America/Santiago
    locale: es_CL
#logging
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
#eureka settings
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 45
    statusPageUrlPath: /infoMembers
    healthCheckUrlPath: /healthMembers
    metadataMap:
      appOwner: TeamWeichafe
      description: members-service
management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream, info, health
    health:
      show-details: always
